Add arm64,armv7 - Add version tag - update docker and python req
automatic-ripping-machine/arm-dependencies pull request #6
Opened 2022-07-27 20:06 UTC by 1337-server

- Adds check to only push docker image when it pushed (not on pr like it currently does)
- Adds Dependabot (Checks docker, pip and python requirements)
- Adds Ubuntu 18 compatibility checks
- Adds the arm architectures (arm64, armv7, armhf) to the build, allowing A.R.M to be run on arm.
   - Added QEMU 
   - Added step to show platform versions available
   - Automatically reads the version from the new VERSION file and pushes to the version & latest tags
   - This significantly increases the build times (Average is 1h)
- Added  `libzbar-dev libzbar0 scons swig` for arm64 dependencies
- Build now compiles MakeMKV ensuring the latest version

- Updated all links to now use the main arm repo
- Bumped version (1.0.3)

### Version bumps
- [Bump beautifulsoup4 from 4.10.0 to 4.11.1](https://github.com/1337-server/arm-dependencies/commit/901f64457d77673a2d96cad7adc91cbab5ee327c)
- [Bump soupsieve from 2.3.1 to 2.3.2.post1 (](https://github.com/1337-server/arm-dependencies/commit/df63d3e206fda5b417f3287c7f56cae628a7d318)
- [Bump cffi from 1.15.0 to 1.15.1 (](https://github.com/1337-server/arm-dependencies/commit/f3aca97bc978d2e3357f32b41783044bb4091835)
- [Bump flask-wtf from 1.0.0 to 1.0.1 (](https://github.com/1337-server/arm-dependencies/commit/24283a8979380f0011ef0b810641c6fe7f7b50b7)
- [Bump xmltodict from 0.12.0 to 0.13.0 (](https://github.com/1337-server/arm-dependencies/commit/cdc92461cf1c527ab210f683a52e3a8f583a0280)
- [Bump sqlalchemy from 1.4.32 to 1.4.39 (](https://github.com/1337-server/arm-dependencies/commit/e9c08f6f790d30b2d396c303396784b7dd65f874)
- [Bump psutil from 5.9.0 to 5.9.1 (](https://github.com/1337-server/arm-dependencies/commit/4c830553911d050f72776a699aa1d5c879672ab0)
- [Bump apprise from 0.9.7 to 0.9.9 (](https://github.com/1337-server/arm-dependencies/commit/3d1e4e5fe426fdc15fededade8d32c6bfdb8ea34)
- [Bump urllib3 from 1.26.9 to 1.26.10 (](https://github.com/1337-server/arm-dependencies/commit/00ab6de0f7c51fed12303708bee7b0f30988fcb1)
- [Bump certifi from 2021.10.8 to 2022.6.15 (](https://github.com/1337-server/arm-dependencies/commit/80c4cc36357a1a8e54020c7214a891c35f3ee079)
[Bump actions/setup-python from 2 to 4 (](https://github.com/1337-server/arm-dependencies/commit/b478e5ef251e6ed0ac86893037090b526e4e9369)

2022-07-28 01:08 UTC, 1337-server commented on .github/workflows/publish-image.yml
> +                      ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
Push to both the branch tag (using `latest` for the default branch) and the version tag from the contents of the version file

non default branches version file should be updated with non-standard semantic versions, e.g. 
- `dev-1.0.1`
- `indev-1.0.1`
- etc

As using normal versions will overwrite the default versions, for example.
A version 1.0.1 inside the indev branch will overwrite the main branch 1.0.1 on docker hub if allowed to push.

2022-07-28 01:08 UTC, 1337-server commented on .github/workflows/publish-image.yml
> +                if: github.event_name != 'pull_request'
Only push if its not a PR

2022-07-28 01:08 UTC, 1337-server commented on .github/workflows/publish-image.yml
> +                    dst: ${{ env.REGISTRY }}/${{ github.repository_owner }}/arm-dependencies:${{ env.TAG }},${{ env.REGISTRY }}/${{ github.repository_owner }}/arm-dependencies:${{ env.VERSION }}
Push to both branch tag and version

also update github.actor

2022-07-28 01:08 UTC, 1337-server commented on .github/workflows/ubuntu18.yml
> +        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
Run setup for Ubuntu 18, run a matrix checking 4 python versions for pip dependencies and fail check if any deps can't be found/installed.

This help quickly check if a new updated package can't be found on specific python version on Ubuntu 18.

2022-07-28 01:08 UTC, 1337-server commented on .github/workflows/version_bump.yml
> +          branch: ${{ github.head_ref }}
This is taken from the Dependabot GitHub.

It's designed to automatically bump the version when Dependabot makes a PR, it doesn't work currently and will need more time of testing/debugging.

2022-07-28 01:08 UTC, 1337-server commented on Dockerfile
> +HEALTHCHECK --interval=5m --timeout=15s --start-period=30s CMD /healthcheck.sh
Copy healthcheck and run it every 5 mins

Allows arm to show unhealthy if anything is broken inside the container

2022-07-28 03:10 UTC, shitwolfymakes commented
Fantastic work!

2022-07-30 00:49 UTC, shitwolfymakes requested changes

2022-07-30 00:50 UTC, 1337-server commented on .github/dependabot.yml
> +    open-pull-requests-limit: 20
If it's updated frequently, 10 should be fine. But for the initial PR, 10 wasn't enough.

2022-07-31 16:49 UTC, shitwolfymakes commented on .github/dependabot.yml
> +    open-pull-requests-limit: 20
Sounds good

2022-07-31 17:38 UTC, shitwolfymakes approved these changes

2022-07-31 17:38 UTC, merged